const SIGNALS = {
  "driving-results": { name: "Driving Results (Impact)", description: "Delivering business value and measurable outcomes" },
  "handling-ambiguity": { name: "Handling Ambiguity", description: "Operating when requirements unclear, priorities shift" },
  "conflict-resolution": { name: "Conflict Resolution", description: "Navigating disagreements with peers, managers, cross-functional partners" },
  "growing-continuously": { name: "Growing Continuously", description: "Seeking feedback, learning from mistakes" },
  "communicating-effectively": { name: "Communicating Effectively", description: "Conveying complex ideas, tailoring message to audience" },
  "ownership": { name: "Ownership", description: "Taking full responsibility start to finish" },
  "leadership-influence": { name: "Leadership & Influence", description: "Aligning people around a vision, leading without authority" },
  "mentorship": { name: "Mentorship", description: "Investing in others, growing talent density" },
  "domain-expertise": { name: "Domain Expertise", description: "Deep knowledge of the company, industry, or technical domain" },
};

const CATEGORIES = {
  "execution-delivery": {
    name: "Execution & Delivery",
    questionTypes: ["tough-project", "deadlines", "blockers", "trade-offs", "high-stakes-call", "roadmap"],
  },
  "technical-judgement": {
    name: "Technical Judgement",
    questionTypes: ["failure", "big-tech-decision", "scaling", "innovation"],
  },
  "leadership-people": {
    name: "Leadership & People",
    questionTypes: ["conflict", "underperformance", "growing-team", "motivating-team", "good-em"],
  },
  "impact-outcomes": {
    name: "Impact & Outcomes",
    questionTypes: ["culture-impact", "above-and-beyond", "results"],
  },
  "frameworks-leadership": {
    name: "Frameworks — Leadership & People",
    questionTypes: ["fw-high-performing-team", "fw-management-style", "fw-scaling-org", "fw-stakeholder-management", "fw-strategy-to-delivery", "fw-operational-balance"],
  },
  "frameworks-technical": {
    name: "Frameworks — Technical & Execution",
    questionTypes: ["fw-technical-excellence", "fw-handling-ambiguity", "fw-prioritization", "fw-engineering-culture", "fw-incident-management", "fw-decision-making"],
  },
  "recruiter-screen": {
    name: "Recruiter Screen",
    questionTypes: ["screen-intro", "screen-why-role", "screen-why-leave", "screen-leadership-scope", "screen-sre-depth", "screen-payments-domain", "screen-questions-for-them", "screen-observability", "screen-aiops", "screen-streaming-pipelines", "screen-scaling-org", "screen-incident-response", "screen-cross-functional"],
  },
};

const QUESTION_TYPES = {
  "tough-project":    { name: "Tough Projects",           category: "execution-delivery",  signals: ["driving-results", "ownership"] },
  "deadlines":        { name: "Deadlines",                category: "execution-delivery",  signals: ["driving-results", "ownership"] },
  "blockers":         { name: "Blockers",                 category: "execution-delivery",  signals: ["ownership", "leadership-influence"] },
  "trade-offs":       { name: "Trade-offs",               category: "execution-delivery",  signals: ["communicating-effectively", "driving-results"] },
  "high-stakes-call": { name: "High Stakes Technical Call",category: "execution-delivery", signals: ["ownership", "driving-results"] },
  "roadmap":          { name: "Roadmap",                  category: "execution-delivery",  signals: ["communicating-effectively", "driving-results"] },
  "failure":          { name: "Failures",                 category: "technical-judgement",  signals: ["growing-continuously"] },
  "big-tech-decision":{ name: "Big Tech Decisions",       category: "technical-judgement",  signals: ["driving-results", "ownership"] },
  "scaling":          { name: "Scaling",                  category: "technical-judgement",  signals: ["leadership-influence", "driving-results"] },
  "innovation":       { name: "Innovations",              category: "technical-judgement",  signals: ["growing-continuously", "driving-results"] },
  "conflict":         { name: "Conflict",                 category: "leadership-people",   signals: ["conflict-resolution"] },
  "underperformance": { name: "Dealing Underperformance", category: "leadership-people",   signals: ["mentorship", "ownership"] },
  "growing-team":     { name: "Building / Growing Team",  category: "leadership-people",   signals: ["leadership-influence", "mentorship"] },
  "motivating-team":  { name: "Motivating The Team",      category: "leadership-people",   signals: ["leadership-influence"] },
  "good-em":          { name: "Good Engineering Manager", category: "leadership-people",   signals: ["leadership-influence", "mentorship"] },
  "culture-impact":   { name: "Culture Impact",           category: "impact-outcomes",     signals: ["leadership-influence"] },
  "above-and-beyond": { name: "Going Above and Beyond",   category: "impact-outcomes",     signals: ["ownership", "driving-results"] },
  "results":          { name: "Results",                  category: "impact-outcomes",     signals: ["driving-results"] },
  "fw-high-performing-team":  { name: "High-Performing Teams",     category: "frameworks-leadership",  signals: ["leadership-influence", "mentorship"], isFramework: true },
  "fw-management-style":      { name: "Management Style",          category: "frameworks-leadership",  signals: ["leadership-influence", "mentorship"], isFramework: true },
  "fw-scaling-org":           { name: "Scaling Organizations",     category: "frameworks-leadership",  signals: ["leadership-influence", "driving-results"], isFramework: true },
  "fw-stakeholder-management":{ name: "Stakeholder Management",    category: "frameworks-leadership",  signals: ["communicating-effectively", "leadership-influence"], isFramework: true },
  "fw-strategy-to-delivery":  { name: "Strategy → Delivery",        category: "frameworks-leadership",  signals: ["leadership-influence", "driving-results"], isFramework: true },
  "fw-operational-balance":   { name: "Keeping the Lights On / Operational Balance", category: "frameworks-leadership", signals: ["driving-results", "ownership"], isFramework: true },
  "fw-technical-excellence":  { name: "Technical Excellence",      category: "frameworks-technical",   signals: ["driving-results", "ownership"], isFramework: true },
  "fw-handling-ambiguity":    { name: "Handling Ambiguity",        category: "frameworks-technical",   signals: ["handling-ambiguity", "ownership"], isFramework: true },
  "fw-prioritization":        { name: "Prioritization",            category: "frameworks-technical",   signals: ["driving-results", "communicating-effectively"], isFramework: true },
  "fw-engineering-culture":   { name: "Engineering Culture",       category: "frameworks-technical",   signals: ["leadership-influence", "growing-continuously"], isFramework: true },
  "fw-incident-management":   { name: "Incident Management",       category: "frameworks-technical",   signals: ["ownership", "leadership-influence"], isFramework: true },
  "fw-decision-making":       { name: "Technical Decision Making", category: "frameworks-technical",   signals: ["driving-results", "communicating-effectively"], isFramework: true },
  "screen-intro":              { name: "Tell Me About Yourself",   category: "recruiter-screen", signals: ["communicating-effectively", "driving-results"] },
  "screen-why-role":           { name: "Why This Role / Company",  category: "recruiter-screen", signals: ["domain-expertise", "driving-results"] },
  "screen-why-leave":          { name: "Why Leaving Current Role", category: "recruiter-screen", signals: ["growing-continuously", "driving-results"] },
  "screen-leadership-scope":   { name: "Leadership Scope & Scale", category: "recruiter-screen", signals: ["leadership-influence", "mentorship"] },
  "screen-sre-depth":          { name: "SRE Experience & Expertise",category: "recruiter-screen", signals: ["driving-results", "ownership"] },
  "screen-payments-domain":    { name: "Payments Domain Knowledge",category: "recruiter-screen", signals: ["domain-expertise", "ownership"] },
  "screen-questions-for-them": { name: "Questions to Ask Recruiter",category: "recruiter-screen", signals: ["communicating-effectively", "domain-expertise"] },
  "screen-observability":      { name: "Observability Platform",   category: "recruiter-screen", signals: ["driving-results", "ownership"] },
  "screen-aiops":              { name: "AIOps / ML Engine",        category: "recruiter-screen", signals: ["driving-results", "ownership"] },
  "screen-streaming-pipelines":{ name: "Streaming Pipelines",      category: "recruiter-screen", signals: ["driving-results", "ownership"] },
  "screen-scaling-org":        { name: "Scaling the Org",          category: "recruiter-screen", signals: ["leadership-influence", "mentorship"] },
  "screen-incident-response":  { name: "Incident Response & Postmortems", category: "recruiter-screen", signals: ["ownership", "leadership-influence"] },
  "screen-cross-functional":   { name: "Cross-Functional Partnership",    category: "recruiter-screen", signals: ["communicating-effectively", "leadership-influence"] },
};

const STORIES = [
  {
    id: "kafka-oom",
    title: "Kafka OOM 3am Incident",
    domains: ["infra", "data"],
    questionTypes: ["high-stakes-call", "tough-project", "above-and-beyond"],
    signals: ["ownership", "leadership-influence"],
    card: {
      c: "Kafka cluster OOM at 3am — entire messaging infra down, dozens of services impacted, customer-facing with regulatory risk.",
      a: [
        "Convened bridge call, split: one on root cause, one on remediation, I handled comms",
        "Doubled heap, restarted brokers sequentially, monitored ISR + consumer lag",
        "15-min leadership updates so they didn't disrupt engineers",
        "Led blameless post-mortem after stabilization",
      ],
      r: "Service restored in 45 min. Drove systemic fixes: automated heap monitoring, self-healing scripts, clearer runbooks. Eventually migrated to MSK.",
      l: "Built deep empathy for on-call engineers. Now prioritize automation and psychological safety during incidents.",
    },
    probes: {
      "was kafka on-prem or managed": "Self-managed on AWS EC2. MSK wasn't mature enough at the time. We owned clusters, configs, and ops.",
      "why didn't first responders fix it": "OOM across all brokers required deep JVM tuning and Kafka internals knowledge. My pre-prepared notes let me act quickly.",
      "how did you ensure no data loss": "Restarted brokers sequentially, checked ISR before/after each restart, monitored consumer lag and rebalance events.",
      "what did you change afterwards": "Automated heap sizing + scaling policies. Wrote formal runbooks. Advocated successfully for moving to MSK.",
    },
  },
  {
    id: "terraform-golden-path",
    title: "Terraform Golden Path",
    domains: ["infra"],
    questionTypes: ["big-tech-decision", "trade-offs", "innovation", "culture-impact"],
    signals: ["driving-results", "leadership-influence", "communicating-effectively"],
    card: {
      c: "Devs frustrated — ticket queue for IAM, networking, CI/CD, K8s configs. Security felt like gatekeepers. Inconsistent standards, slow delivery, rising friction.",
      a: [
        "Built Terraform modules — full solutions with least-privilege IAM, encryption, logging, cost tagging baked in",
        "Integrated OPA/Sentinel guardrails into CI/CD — shift-left from manual review",
        "CLI tool (svc init) — one command → compliant repo with pipeline in under an hour",
        "Drove adoption via office hours, examples, roadshows — 'guardrails, not gates'",
      ],
      r: "85% adoption in 3 months. IAM/network incidents down 60%. Deploy time: weeks → hours. Near-zero audit findings.",
      l: "Won trust by making the safe path the easiest path. RFC-based exceptions for edge cases.",
    },
    probes: {
      "how did you handle pushback": "Allowed RFC-based exceptions. Communicated empathetically — guardrails not gates.",
      "how did you measure adoption": "Adoption %, reduced exceptions, developer NPS/feedback.",
      "what about teams that didn't adopt": "Early adopters influenced templates, which gave them ownership. Roadshows captured pain points.",
    },
  },
  {
    id: "cloud-migration",
    title: "Cloud Migration (Top-Down & Bottom-Up)",
    domains: ["infra"],
    questionTypes: ["tough-project", "blockers", "trade-offs", "results"],
    signals: ["driving-results", "leadership-influence", "ownership"],
    card: {
      c: "Large-scale cloud migration mandate. Execs wanted cost reduction + compliance. Engineers skeptical — feared bureaucracy and less autonomy.",
      a: [
        "Top-down: partnered with CISO + directors on KPIs (% migrated, MTTR, compliance)",
        "Bottom-up: developer portal with Terraform templates, policy-as-code in CI/CD",
        "Bridged with team-level scorecards (compliance, cost, deploy time) — transparent, not punitive",
        "Roadshows + early adopter workshops for ownership",
      ],
      r: "70% of targeted workloads migrated in 12 months. Zero high-severity audit findings. Deploy time: 2-3 weeks → under 1 day.",
      l: "Cloud transformation is 50% technology, 50% culture. Top-down provides air cover, bottom-up makes it sustainable.",
    },
    probes: {
      "how did you convince execs": "Linked KPIs to business risk (audit penalties, infra spend) and opportunity (faster launches).",
      "what resistance from engineers": "Initial pushback — turned critics into co-creators of the templates.",
      "what would you do differently": "Invest earlier in change champions or embed platform engineers in product teams.",
    },
  },
  {
    id: "sbom-vuln",
    title: "SBOM Vulnerability Management",
    domains: ["infra"],
    questionTypes: ["innovation", "results", "blockers", "above-and-beyond"],
    signals: ["driving-results", "ownership", "conflict-resolution"],
    card: {
      c: "Friction between engineering and CISO security team. Devs getting unactionable vuln alerts — mostly from base images they didn't own. Alert fatigue, wasted effort, broken trust.",
      a: [
        "Reframed from 'send all alerts' to 'vulnerability intelligence as a service'",
        "Built streaming graph-based ownership model — Kafka → MongoDB, CVE→Layer→App→Owner",
        "Automated ticket routing: base image vulns → platform team, app-level → owning team",
        "Partnered with CISO, platform leads for shared understanding",
      ],
      r: "92% reduction in unactionable alerts. MTTR for base image vulns: 45 days → 6 days. 99% automated ownership mapping.",
      l: "Positioned platform team as enabler, not blocker. Rebuilt trust by removing noise.",
    },
    probes: {
      "what do you mean by graph model": "Directed graph — each node is a component (base image, library, app), edges are dependencies. Trace any CVE to its true origin and owner.",
      "why mongodb not neo4j": "Graph was shallow, already had Mongo in stack. Modeled edges with array fields. Considered Neo4j but use case didn't need heavy graph operations.",
    },
  },
  {
    id: "scaling-teams",
    title: "Scaling Teams 25→50 (Managing Managers)",
    domains: ["infra", "data", "general"],
    questionTypes: ["scaling", "growing-team", "good-em"],
    signals: ["leadership-influence", "mentorship"],
    card: {
      c: "Org doubled (25→50 engineers) in a year. Couldn't add formal managers — only engineers and contractors. Delivery needed structure but hierarchy wasn't an option.",
      a: [
        "Created Tech-Lead Operating Model — 5 senior ICs each owning a domain (player-coaches)",
        "Defined clear swimlanes — ownership boundaries + interfaces between streams",
        "Bi-weekly Tech Leads Forum for priorities, dependencies, resourcing",
        "Weekly 1:1s coaching each lead on stakeholder mgmt, estimation, conflict resolution",
        "Dashboards + shared OKRs for visibility without bureaucracy",
      ],
      r: "Delivery capacity scaled 2x in 6 months. Zero new management overhead. One tech lead later promoted to EM. Model became blueprint adopted by 2 other orgs.",
      l: "Leadership isn't about titles — it's about creating a system where accountability, decision-making, and trust scale faster than hierarchy.",
    },
    probes: {
      "how did you pick the tech leads": "Identified engineers already informally leading. Formalized it with clear domain ownership.",
      "what about contractor output": "Improved significantly — communication flowed through empowered leads rather than waiting for top-down direction.",
    },
  },
  {
    id: "finops-vision",
    title: "Vision: Future of Cloud Ops (FinOps)",
    domains: ["infra"],
    questionTypes: ["innovation", "results", "roadmap"],
    signals: ["driving-results", "leadership-influence"],
    card: {
      c: "Strategic mandate to modernize infra (VMs→Containers). Adoption slow — engineers treated infra as 'free', no visibility into cost trade-offs.",
      a: [
        "Partnered with platform eng to ingest usage metrics against cloud rate cards",
        "Built projection engine — teams plug in throughput, see side-by-side P&L of As-Is vs Shared Cluster",
        "Integrated into developer portal — self-serve, instant feedback loop",
      ],
      r: "Identified $12.5M in annualized savings in first quarter. Cost became an engineering constraint like latency or availability.",
      l: "Shifted cost accountability left. Changed the conversation from mandate to empowerment.",
    },
    probes: {},
  },
  {
    id: "drift-modernization",
    title: "DRIFT Modernization",
    domains: ["data"],
    questionTypes: ["tough-project", "big-tech-decision", "high-stakes-call", "results"],
    signals: ["driving-results", "ownership", "leadership-influence"],
    card: {
      c: "Enterprise data fabric — 2B records/day, 300 sources, Hadoop/Spark batch. Policy checks 4-6hrs late. CISO: 'We're operating blind.'",
      a: [
        "Coalition & Pave — won Security/Identity first, absorbed legacy complexity for rest (CDC + file-shredder)",
        "Kafka single front door → Flink hot path → Iceberg (coexist with Spark, not replace)",
        "OPA + broadcast state for in-flight governance, zero-downtime policy updates",
        "Coached Rahul (Iceberg compaction) + Emma (RocksDB state) — team became self-sufficient",
      ],
      r: "Latency 6hrs → <1min. Zero disruption to downstream Spark jobs. 300 teams onboarded without redesigning their systems.",
      l: "Hardest part wasn't tech — it was organizational inertia. Made the right way the easy way.",
    },
    probes: {
      "what made it hard": "3 fronts: correctness at scale (billions of events, late-event handling), Spark coexistence (Iceberg as peace treaty), and 300 team owners who hadn't touched integrations in years.",
      "your role vs team": "I owned overall technical direction + delivery strategy. Tech leads owned vertical slices and implementation.",
      "how did you measure success": "Three dimensions: business continuity (zero downtime), operational metrics (latency), organizational leverage (other teams reused the blueprint).",
      "why flink over spark streaming": "True streaming not micro-batch. Better state management. Millisecond latency. Exactly-once at scale.",
    },
  },
  {
    id: "scout-led",
    title: "SCOUT — ML Reliability Platform (Led)",
    domains: ["data"],
    questionTypes: ["tough-project", "innovation", "big-tech-decision", "results"],
    signals: ["driving-results", "ownership"],
    card: {
      c: "Millions of operational records monthly across ServiceNow, CAI — different formats, critical info buried in free-text. No way to correlate incidents or spot patterns.",
      a: [
        "Normalized fragmented data into single schema — without clean data, ML produces noise",
        "AWS-native serverless: SageMaker for managed training. 110ms latency budget for real-time triage",
        "Ensemble meta-selector maximizing precision + recall within performance constraint",
        "Treated internal engineering as customer — relevance feed, not generic dashboard",
      ],
      r: "Triage time cut 55%. Recurring incidents down 36%. Precision: 68%→89%. First real-time view of operational risk for leadership.",
      l: "Data quality before model quality. Adoption comes from treating internal users as customers.",
    },
    probes: {},
  },
  {
    id: "scout-helped",
    title: "SCOUT — ML Platform (Supported)",
    domains: ["data"],
    questionTypes: ["innovation", "above-and-beyond"],
    signals: ["mentorship", "ownership", "growing-continuously"],
    card: {
      c: "SCOUT team blocked on data ingestion, normalization, architecture, and noisy/unlabeled data. They owned model dev but were stuck.",
      a: [
        "Leaned into DS background to sharpen ML problem framing — cluster similar incidents, not predict unreliable categories",
        "Guided labeling strategy: what labels matter, confidence thresholds, fallback logic",
        "Led cloud data architecture: SNS/SQS → Lambda → S3 → SageMaker → DynamoDB",
        "Introduced evaluation guardrails: precision/recall per category, drift detection, silhouette scores",
      ],
      r: "First clean dataset across SNOW+CAI. 7-9 themes identified. 30-40% noise reduction. Team adopted cloud-native AIOps foundation.",
      l: "Strengthened DS hands-on credibility. Became go-to for ML partnerships in the org.",
    },
    probes: {},
  },
  {
    id: "app-dependencies",
    title: "Application Dependencies (Ambiguity→Alignment)",
    domains: ["data", "infra"],
    questionTypes: ["tough-project", "blockers"],
    signals: ["handling-ambiguity", "leadership-influence", "communicating-effectively"],
    card: {
      c: "When a critical system went down, the first 20 min went to figuring out *who was even affected*, not fixing it. We had dependency data but it couldn't tell a dead app from a fine one — a payment-gateway dependency (dead) and a reporting-API dependency (fine) were recorded identically. Nobody owned what 'critical' meant; every team defined 'dependency' differently (infra=hosting, app owners=data flows, risk=recovery chains).",
      a: [
        "Workshops across infra / app owners / risk — reframed the question: 'what decision are you trying to make with this?' not 'what are your dependencies'",
        "Built a criticality model: rules-based, not self-declared — computed from objective criteria (recovery-time, backs a critical business service) into tiers (critical / recovery / partial / no-recovery)",
        "Criticality inherited — an app is critical if something critical depends on it, traced through the chain = true blast radius. Owners attest; classification applied uniformly + reason attached (auditable)",
        "Decomposed into pods: taxonomy/criticality model, data layer, impact-viz, attestation workflow",
        "Pivoted from Neo4j to Java API + JS graph viz — within existing stack",
      ],
      r: "Real-time blast radius in incidents — right people on the bridge in minutes, no over-paging unaffected teams. Risk audit prep halved (accurate recovery chains). Adopted by 1,300+ critical apps; unblocked stalled migration planning as a second-order benefit.",
      l: "In ambiguity, the breakthrough is reframing the question, not building faster — 'what breaks when this breaks, and who must act?' Alignment on the why comes before architecture.",
    },
    probes: {
      "why not neo4j": "POC revealed steep operational overhead + limited in-house expertise. Pivoted to Java + JS viz on Postgres. Delivered in 2 sprints.",
    },
  },
  {
    id: "tibco-migration",
    title: ".NET TIBCO EMS Migration",
    domains: ["infra"],
    questionTypes: ["tough-project", "deadlines", "trade-offs"],
    signals: ["driving-results", "ownership"],
    card: {
      c: "Enterprise approval workflow on aging .NET + TIBCO EMS. Platform unstable, nearing EOL. Global directive to retire TIBCO. Deeply interconnected — big-bang rewrite not feasible.",
      a: [
        "Domain + capability mapping workshops → identified core functions + dependencies",
        "Strangler Fig approach: Solace PubSub+ as hybrid event backbone (private cloud + AWS EKS)",
        "API facade + message bridge — route events to both systems during gradual migration",
        "Walking skeleton first — minimal end-to-end flow before expanding",
        "Jira initiative with epics per vertical slice, dependency matrix for sequencing",
        "Everything codified: Terraform + Helm for repeatable, auditable deployments",
      ],
      r: "First AWS-backed flow in 12 weeks, zero downtime. Incidents down 50%, approval latency improved 30%. Blueprint reused across bank.",
      l: "Architectural decomposition + structured execution planning. Parallel team delivery through epic structure.",
    },
    probes: {
      "how ensure no data loss": "Solace persistent queues with built-in durability. Clear retention/expiry policies. Dead-letter queue + replay for forensics.",
      "how did you codify": "Terraform for all infra (VPCs, EKS, IAM, Solace brokers). Helm charts for app + Solace config. Everything in Git, CI/CD pipelines, full audit trail.",
      "how measure success": "Three dimensions: business continuity (zero downtime), operational metrics (50% fewer incidents), organizational leverage (blueprint reused).",
    },
  },
  {
    id: "neo4j-failure",
    title: "Neo4j Wrong Call (Failure Story)",
    domains: ["infra", "data"],
    questionTypes: ["failure"],
    signals: ["growing-continuously"],
    card: {
      c: "Needed to map app dependencies for risk + compliance. Problem screamed 'graph database.' Chose Neo4j — seemed perfect fit.",
      a: [
        "Team spent 8 weeks building with Neo4j + Java API",
        "Cypher queries were brittle, inefficient, hard to debug",
        "SREs couldn't operate it — no standard monitoring, no automated backups",
        "Missed first major deadline. Project flagged red.",
      ],
      r: "Owned the mistake to director + stakeholders: 'I made the wrong architectural call.' Pivoted to JS visualization + Java/Postgres. Delivered in 2 sprints.",
      l: "Moving fast is easy — moving fast in the right direction requires deep awareness of your team's capacity, not just a technology's potential. Never adopt new tech without capability + operational readiness check.",
    },
    probes: {
      "what would you do differently": "Run a 2-week spike with SRE before committing. Evaluate operational readiness, not just technical fit.",
      "how did stakeholders react": "Trust dipped initially but earned it back through fast pivot and transparent communication.",
    },
  },
  {
    id: "kafka-vs-solace",
    title: "Kafka vs Solace (ARB Conflict)",
    domains: ["infra"],
    questionTypes: ["conflict", "trade-offs", "big-tech-decision"],
    signals: ["conflict-resolution", "communicating-effectively", "leadership-influence"],
    card: {
      c: "Migrating .NET+TIBCO to Java microservices. Proposed Kafka. ARB pushed back — Solace is sanctioned TIBCO replacement, better JMS semantics. Room divided.",
      a: [
        "Round 1: Side-by-side POC — same workflow on both. Data came back strong for Kafka",
        "Still resisted. Realized issue wasn't technical — it was institutional trust",
        "Round 2: Mapped Kafka event flows to Citi audit control IDs (SOX/OCC compliance)",
        "Invited Distinguished Engineer (Citi Fellow) as neutral voice — changed tone from positions to trade-offs",
        "Proposed controlled-use model: specific config patterns, post-impl compliance review, 6-month Solace rollback path",
      ],
      r: "Passed with 75%+ approval. Deployed first Kafka-based approval flow — millions of messages, zero data loss, full audit traceability.",
      l: "Alignment isn't about winning consensus — it's about earning trust. Translate to the language others trust. Invite respected voices to widen confidence.",
    },
    probes: {},
  },
  {
    id: "governance-pushback",
    title: "Governance Pushback on Streaming",
    domains: ["data"],
    questionTypes: ["conflict", "trade-offs"],
    signals: ["conflict-resolution", "communicating-effectively"],
    card: {
      c: "Moving DRIFT from batch to streaming. Governance team pushed back — their anomaly detection relied on batch (daily record counts vs baselines). Feared losing safety net.",
      a: [
        "Didn't dismiss concern — reframed goal from 'preserve batch' to 'preserve trust'",
        "Designed streaming-native verification: sliding windows + temporal aggregates in Flink",
        "Hourly checkpoints comparing rolling counts against dynamic historical averages in Iceberg",
        "Deviations >20% → real-time Prometheus alerts",
      ],
      r: "Governance approved the transition. Gained earlier detection — data drift within an hour instead of next day's batch.",
      l: "Meet stakeholders where their concern lives, not where your architecture lives.",
    },
    probes: {},
  },
  {
    id: "flink-vs-spark-arb",
    title: "Flink vs Spark (ARB Technical Conflict)",
    domains: ["data", "infra"],
    questionTypes: ["conflict", "big-tech-decision"],
    signals: ["conflict-resolution", "driving-results", "leadership-influence"],
    card: {
      c: "Core infra platform on 6hr batch Hive/Spark pipelines. Security blind spot — SOC2/ISO 27001 at risk. Proposed Flink. ARB blocked — 'stay with Spark Structured Streaming.'",
      a: [
        "Stopped arguing technical superiority. Acknowledged ARB's risk framing as valid",
        "Proposed data-driven partnership: 4-week A/B pilot, same production workload, Flink vs Spark Streaming",
        "Instrumented for their concerns: P99 latency, cost, fault-tolerance, SLA compliance",
        "Made ARB leads validation partners — invited to weekly pilot reviews",
        "Documented clear exit criteria + decommission plan if Flink underperformed",
      ],
      r: "Flink: 99.9% uptime, 6hrs→<1min latency, 40% fewer nodes. ARB unanimously approved. CTO cited validation framework as 'blueprint for responsible innovation.'",
      l: "Framing matters. We weren't betting the platform — we were conducting a safe, evidence-based experiment.",
    },
    probes: {},
  },
  {
    id: "pod4-alignment",
    title: "Pod 4 Alignment (Competing Implementations)",
    domains: ["infra"],
    questionTypes: ["conflict"],
    signals: ["conflict-resolution", "leadership-influence"],
    card: {
      c: "Pod 4 mid-migration TIBCO→Solace, 80% done. Principal engineer from another pod disagreed with approach, built parallel implementation in same codebase. Two competing impls, team in-fighting, deadline at risk.",
      a: [
        "Separated architecture problem from people problem — different interventions needed",
        "Architecture: reframed from 'whose design is better' to sustainability — two impls = cognitive load + silent divergence",
        "People: protected Pod 4's autonomy — they'd done architecture review, team consensus, structured execution. Overruling them would kill psychological safety org-wide",
        "Direct conversation with principal: 'challenging design isn't the problem, bypassing process is. Writing parallel code to win an argument is a liability.'",
        "Deprecated his implementation. Added lightweight design review gate for cross-team deps",
      ],
      r: "Migration completed on schedule. Single agreed implementation. Pod 4's confidence in their decision-making authority intact.",
      l: "Difference between alignment and agreement. Influence is a skill, not a status — when a senior IC bypasses it, that's a coaching conversation.",
    },
    probes: {},
  },
  {
    id: "underperformer-coach-up",
    title: "Managing Underperformer (Coach Up)",
    domains: ["general"],
    questionTypes: ["underperformance"],
    signals: ["mentorship", "ownership"],
    card: {
      c: "Mid-level engineer underperforming — missing sprint goals, code failing QA. Seemed disengaged. Impacting team morale and delivery reliability.",
      a: [
        "Candid 1:1 — identified root cause: low confidence + unclear expectations",
        "Co-created 60-day improvement plan with specific, measurable goals",
        "Paired with senior mentor for code review and design help",
        "Weekly check-ins for real-time feedback. Celebrated small wins publicly.",
      ],
      r: "Defect rate dropped 35%. Delivery reliability improved within 2 sprints. Later took ownership of a core service redesign.",
      l: "Reinforced coaching-based leadership. Address root cause, not symptoms.",
    },
    probes: {
      "what if they hadn't improved": "Would have moved to formal PIP with HR. The 60-day plan was designed to be fair and documented either way.",
    },
  },
  {
    id: "underperformer-pip",
    title: "Managing Underperformer (PIP → Exit)",
    domains: ["general"],
    questionTypes: ["underperformance"],
    signals: ["ownership", "leadership-influence"],
    card: {
      c: "Engineer (Nate) consistently underperforming — missed deadlines, recurring code quality issues, failed to follow through on action items despite informal coaching. Affecting team morale.",
      a: [
        "Designed SMART-goal PIP with HR: defects from 12→<5/sprint, complete stories for 3 consecutive sprints, pair programming 2x/week",
        "Weekly 1:1 coaching, code review feedback, bi-weekly HR check-ins",
        "Documented everything. Recognized incremental progress. Framed PIP as support, not punishment.",
      ],
      r: "After 90 days, metrics hadn't improved. Made difficult decision to terminate. Handled professionally — transparency, documentation, protecting team morale. Sprint velocity improved 20% in next cycle.",
      l: "Culture of accountability AND fairness. Team saw that performance issues are addressed thoughtfully, with real opportunity but also clear consequences.",
    },
    probes: {},
  },
  {
    id: "misjudged-engineer",
    title: "Misjudged Engineer (Wrong Assumption)",
    domains: ["general"],
    questionTypes: ["failure", "growing-team"],
    signals: ["growing-continuously", "mentorship"],
    card: {
      c: "Two new engineers during major release. One came across as 'rockstar' — confident, proactive, constantly communicating. Other was quieter, double-checking before sharing. Instinct said first was high performer.",
      a: [
        "Before acting on gut feeling, pulled objective data — defects fixed, resolution time, reopen rates",
        "Results: nearly identical output. Roughly 40 defects each, one-day difference in turnaround.",
        "Humbling realization: mistaken communication style for performance difference. Signal-visibility gap, not performance gap.",
        "Met with quieter engineer, praised results, coached on proactive communication",
      ],
      r: "Within weeks he shared updates more confidently. Became one of our most trusted developers.",
      l: "Confidence and competence aren't the same thing. Treat instinct as hypothesis, not conclusion — validate with data. Permanently shaped how I lead.",
    },
    probes: {},
  },
  {
    id: "inclusive-leadership",
    title: "Inclusive Leadership & Diversity",
    domains: ["general"],
    questionTypes: ["culture-impact", "growing-team", "good-em"],
    signals: ["leadership-influence", "mentorship", "growing-continuously"],
    card: {
      c: "Globally distributed org — quieter engineers (often underrepresented groups) struggled to be heard in design discussions. Risked missing good ideas and hurting inclusivity.",
      a: [
        "Rotating meeting leads — not just loudest voices running discussions",
        "Shifted design reviews to include written async input for global team members",
        "Partnered with HR: diverse interview panels + anonymized resume screening",
        "Mentorship pairings: junior engineers from underrepresented groups with senior ICs",
      ],
      r: "+25% team survey 'I feel my opinions are valued.' Diverse hiring improved. Retention up. Quieter engineers started driving key features.",
      l: "Built reputation as 'safe, inclusive, high-performance' culture.",
    },
    probes: {},
  },
  {
    id: "innovation-spikes",
    title: "Encouraged Team Innovation",
    domains: ["general"],
    questionTypes: ["innovation", "motivating-team", "culture-impact"],
    signals: ["growing-continuously", "leadership-influence"],
    card: {
      c: "Deep into large modernization program at Citi. Everyone doing what was convenient — afraid to experiment or break something.",
      a: [
        "Introduced biweekly 'innovation spikes' — alternating Fridays for prototyping",
        "Success measured by learning velocity, not perfection. Celebrated failed demos.",
        "Worked with product leadership to frame as strategic investments, not distractions",
      ],
      r: "One spike → GraphQL prototype cutting REST calls by 50%. Another explored gRPC reducing latency. Evolved into formal API modernization initiative endorsed by architecture leadership.",
      l: "Innovation needs structure and safety, not hackathons and slogans. Team shifted from 'easiest way' to 'best way.'",
    },
    probes: {},
  },
  {
    id: "conflicting-requirements",
    title: "Conflicting Requirements (PM Roadmap)",
    domains: ["general"],
    questionTypes: ["conflict", "trade-offs"],
    signals: ["conflict-resolution", "communicating-effectively", "driving-results"],
    card: {
      c: "CAI portal modernization — roadmap prioritized backend migration + UI polish. Analyzed data: most complaints were about search, not aesthetics. #1 cause of internal churn.",
      a: [
        "Gathered evidence: support tickets, NPS, analytics showing search frustration",
        "Built lightweight POC demonstrating search relevance improvements",
        "Acknowledged PM's delivery concerns. Reframed around shared goal: customer retention",
        "Compromised: re-sequenced roadmap — search earlier, minor UI milestone pushed one sprint",
      ],
      r: "Search success rate improved 40%. User satisfaction scores jumped. Leadership recognized it as most impactful roadmap adjustment that quarter.",
      l: "Customer data must guide the roadmap. Disagreements with PMs are opportunities to co-create better outcomes.",
    },
    probes: {},
  },
  {
    id: "architecture-alignment-greg",
    title: "Architecture Alignment (Greg Story)",
    domains: ["general"],
    questionTypes: ["conflict", "blockers"],
    signals: ["conflict-resolution", "leadership-influence", "communicating-effectively"],
    card: {
      c: "Inherited team with significant internal friction. Long-tenured peer acting as technical gatekeeper, citing vague 'architectural misalignments' to block velocity. Missed deadlines, leadership losing trust.",
      a: [
        "Initiated 'Architecture Alignment' series — invited peer to lead definition of ideal state standards",
        "Translated technical jargon to business outcomes: 'DB access' → 'mitigating delivery risk for Q3'",
        "Implemented live RACI Matrix — moved verbal 'No's into documented framework visible to Director",
        "5-minute acknowledgment rule — all pings acknowledged immediately, resolution scheduled",
      ],
      r: "Unblocked critical DB integration stalled for months. Director noted 'reduction in team temperature.' 20% increase in team velocity. Reclaimed project intake ownership.",
      l: "At senior management level, transparency is the best antidote to politics. Treat obstructionists as consultative partners, center on business value.",
    },
    probes: {},
  },
  {
    id: "communication-planning",
    title: "Communication & Planning Structures",
    domains: ["general"],
    questionTypes: ["results", "good-em", "roadmap"],
    signals: ["communicating-effectively", "driving-results"],
    card: {
      c: "Stepped into chaotic environment mid-project. Communication with business partners broken. Engineering team lacked clarity and direction.",
      a: [
        "Stakeholder mapping (power/interest grid) to tailor cadence and detail level",
        "RACI matrix — eliminated ambiguity on every deliverable",
        "RICE scoring + impact-effort matrices for feature prioritization",
        "Meta's 2-2-2 code review: PRs ≤200 lines, ≤2 reviewers, 2-day turnaround",
      ],
      r: "Delivery cycle cut 35%. Restablished trust with business stakeholders. Team morale and execution speed increased.",
      l: "Structured communication removes ambiguity. Clear processes let talented people do their best work.",
    },
    probes: {},
  },
  {
    id: "cloud-agnostic",
    title: "Cloud Agnostic Infrastructure",
    domains: ["infra"],
    questionTypes: ["big-tech-decision", "trade-offs"],
    signals: ["driving-results", "handling-ambiguity"],
    card: {
      c: "Citi partnered with GCP to expand footprint. Org heavily invested in AWS. Uncertainty — multiple teams had ongoing programs, AWS-native tooling, regulatory deadlines.",
      a: [
        "Led initiative to define consistent deployment model across both clouds",
        "Terraform modules + policy-as-code to abstract provider differences",
        "Built first end-to-end reference implementation, validated with security + compliance",
        "Onboarded early adopters from 3 lines of business",
      ],
      r: "Provisioning lead time reduced ~40%. Created reusable pattern adopted by other internal cloud teams. Positioned org to move workloads without vendor lock-in.",
      l: "Absorb complexity so consuming teams don't have to.",
    },
    probes: {},
  },
  {
    id: "measuring-productivity",
    title: "How I Measure Engineering Productivity",
    domains: ["general"],
    questionTypes: ["good-em", "results"],
    signals: ["driving-results", "communicating-effectively"],
    card: {
      c: "Common interview question — 'how do you measure your team's productivity?'",
      a: [
        "DORA metrics + business/operational metrics — not lines of code or hours",
        "Daily: sprint board blockers, CI/CD status, active incidents",
        "Weekly: lead time from commit to production, deployment frequency",
        "Monthly/quarterly: change failure rate, overall efficiency",
        "Track 'say/do ratio' — plan 50, deliver 20 = planning problem, not people problem",
      ],
      r: "Goal isn't to make people work harder — it's to find where the system is blocked.",
      l: "Measure the system, not the humans.",
    },
    probes: {},
  },
  // ============ RECRUITER SCREEN — Mastercard Director SRE ============
  {
    id: "screen-elevator-pitch",
    title: "Elevator Pitch (Boomerang Narrative)",
    domains: ["screen"],
    questionTypes: ["screen-intro"],
    signals: ["communicating-effectively", "driving-results", "domain-expertise"],
    card: {
      c: "SVP at Citi leading a 20-person global SRE org (US, Europe, India). Previously Tech Lead and Engineering Manager at Mastercard Dublin for three years. This is a boomerang move back to build the European SRE operational presence.",
      a: [
        "At Citi: built SRE from scratch — observability platform (OpenTelemetry, Prometheus, Grafana), AIOps engine (100k+ incidents/month, repeat incidents down 35%), automation pipelines (2B+ events/day, toil reduced 25%)",
        "Led a globally distributed org — US, Europe, India — so I understand what 'owning the European operational presence' means in practice",
        "At Mastercard Dublin: led 10 engineers on infrastructure and on-call — Kubernetes, CI/CD, production operations. I know the Dublin tech hub culture",
        "Deep experience across Linux, containers (Kubernetes), monitoring, incident command, and ITSM workflows (ServiceNow)",
      ],
      r: "Track record of building SRE organizations from scratch at enterprise scale — combining technical depth in core infrastructure with leadership across multiple geographies.",
      l: "The Director SRE role in the Distributed Platforms team is where my enterprise SRE experience, my European operational leadership, and my Mastercard knowledge converge — a deliberate return, not a lateral move.",
    },
    probes: {
      "what exactly do you do at citi": "SVP, Engineering Group Manager in Cloud Technology Services. I own the observability, AIOps, and SRE automation platforms across a global engineering org of 20.",
      "what did you do at mastercard": "Tech Lead / Engineering Manager from 2019-2022 in the Dublin office. Led a team of 10 building scalable blockchain infrastructure (Hyperledger Besu, Kubernetes) and the faster payments pilot (FPS2FPS on R3 Corda).",
      "how long have you been at citi": "Since October 2022 — just over three years.",
    },
  },
  {
    id: "screen-why-mastercard",
    title: "Why Mastercard / Why Come Back",
    domains: ["screen"],
    questionTypes: ["screen-why-role"],
    signals: ["domain-expertise", "driving-results", "growing-continuously"],
    card: {
      c: "Left Mastercard in 2022 after three years as Tech Lead/EM in Dublin. Joined Citi to take on a larger scope — building an SRE practice for cloud technology services from the ground up.",
      a: [
        "At Citi I got the broader leadership canvas I needed — 20-person global org, multi-cloud strategy, enterprise observability, AIOps",
        "This role hits exactly what I've been building toward: leading SRE operations in Europe, owning automation and observability, driving operational resilience",
        "I know the Dublin tech hub, the culture, and what it takes to operate critical infrastructure at Mastercard's scale",
        "The Distributed Platforms focus — Linux, VMware, storage, containers — maps directly to the infrastructure I've managed across both companies",
      ],
      r: "This isn't a generic move — it's a deliberate return. I want to bring enterprise-scale SRE maturity back to a company I know, building the European SRE presence from Dublin.",
      l: "The best career moves aren't just steps up — they're steps toward where your experience creates the most impact.",
    },
    probes: {
      "what specifically about payments": "Payments infrastructure has zero tolerance for downtime — every second of unavailability has real monetary and reputational impact. That urgency shaped my SRE philosophy. It's the domain where reliability engineering matters most.",
      "what would you do differently this time": "Last time I was a Tech Lead building hands-on. Now I'd shape the SRE strategy, build the team culture, and drive observability and reliability practices across the Payments Network — a fundamentally different scope.",
      "do you know anyone still there": "It's been a few years so the team may have changed, but I understand the environment, the compliance requirements, and how Mastercard operates.",
    },
  },
  {
    id: "screen-why-leave-citi",
    title: "Why Leaving Citi",
    domains: ["screen"],
    questionTypes: ["screen-why-leave"],
    signals: ["growing-continuously", "driving-results"],
    card: {
      c: "Incredible run at Citi — built the SRE practice, grew the team globally, delivered major platforms. After three-plus years, the foundational work is done and the team is self-sufficient.",
      a: [
        "The observability platform is mature and operational across hundreds of services",
        "The AIOps engine is in production and owned by the team",
        "I've developed the next layer of leadership — tech leads are running independently",
        "I'm now looking for a role where I can apply this experience to mission-critical infrastructure at even higher stakes",
      ],
      r: "Not running from Citi — running toward leading SRE operations in Europe for a company I already know. The Distributed Platforms Director role is exactly where my experience converges.",
      l: "Knowing when your foundational work is complete and the org can thrive without you is a leadership skill. That's how I know it's time.",
    },
    probes: {
      "is there anything pushing you to leave": "No — Citi has been excellent. It's about pull, not push. The Mastercard role is a rare convergence of my SRE expertise, my payments domain knowledge, and a company I already know and respect.",
      "what about counter offer": "I've thought about this carefully. What I want — leading SRE for payments infrastructure — isn't available at Citi. This is a domain-specific move, not a comp negotiation.",
    },
  },
  {
    id: "screen-current-scope",
    title: "Leadership Scope & Scale (Current)",
    domains: ["screen"],
    questionTypes: ["screen-leadership-scope"],
    signals: ["leadership-influence", "mentorship", "driving-results"],
    card: {
      c: "Currently leading a 20-person global engineering organization at Citi — engineers and contractors across the US, Europe, and India. Cloud Technology Services.",
      a: [
        "Hired, mentored, and coached across all levels — mid-level engineers to senior tech leads",
        "Built a tech-lead operating model to scale decision-making without adding management layers",
        "Established OKRs, DORA metrics, and say/do ratio as the operating framework",
        "Run bi-weekly tech lead forums, weekly 1:1s, quarterly career development planning",
        "Present roadmap progress and trade-offs to senior leadership (CTOEAC) regularly",
      ],
      r: "Doubled team throughput. Earned company-wide leadership awards. One tech lead promoted to engineering manager. Model became blueprint adopted by two other organizations.",
      l: "At this level, my impact isn't what I build — it's the system I create for others to deliver at scale.",
    },
    probes: {
      "how many direct reports": "Currently 20 in total — mix of direct reports and tech leads who manage sub-teams. At Mastercard it was a team of 10.",
      "do you manage managers": "I manage tech leads who function as player-coaches — they own domains and have people responsibilities without formal manager titles. I've also managed the transition of a tech lead into a full engineering manager role.",
      "how do you handle remote teams": "Global org across US, Europe, India. Written culture for decisions, async design reviews, time-zone-aware meeting cadences. Tech lead forums bridge the gaps.",
    },
  },
  {
    id: "screen-sre-mastery",
    title: "SRE Experience & Platform Build",
    domains: ["screen"],
    questionTypes: ["screen-sre-depth"],
    signals: ["driving-results", "ownership", "domain-expertise"],
    card: {
      c: "Spent three-plus years at Citi building SRE as a discipline from the ground up for a global cloud technology organization. Before that, ran infrastructure operations and on-call at Mastercard Dublin.",
      a: [
        "Architected observability platform — OpenTelemetry, Prometheus, Grafana — custom alerting correlated across hundreds of services",
        "Built AIOps engine — ML-powered text analytics ingesting 100k+ incidents monthly for predictive analysis and hotspot identification",
        "Drove automation and toil reduction — event pipelines processing 2B+ events daily for real-time metrics and alerting, reducing toil 25%",
        "Established incident response, blameless postmortems, and production readiness — exactly what the JD calls 'operational resilience'",
        "Experience across Linux, containers (Kubernetes), VMware environments, and ITSM workflows (ServiceNow)",
      ],
      r: "Repeat incidents down 35%. Operational toil reduced 25%. Built the SRE culture — not just the tools. The JD's pillars (automation, observability, operational resilience) are literally what I built at Citi.",
      l: "SRE at enterprise scale is three things: technical depth, organizational alignment, and a culture where reliability is everyone's responsibility — not a team name.",
    },
    probes: {
      "what tools do you use": "OpenTelemetry for instrumentation, Prometheus for metrics, Grafana for visualization and alerting. Kafka and Flink for streaming data pipelines. ServiceNow for incident management. All on AWS with some multi-cloud (GCP).",
      "have you done chaos engineering": "We've built production readiness reviews and have automated remediation patterns. Chaos engineering is a natural next step — the Mastercard role's emphasis on it aligns with where I want to push the practice.",
      "how do you measure sre success": "SLIs/SLOs for service reliability, MTTR and incident frequency for operational health, toil reduction percentage for automation maturity, and DORA metrics for delivery velocity.",
    },
  },
  {
    id: "screen-payments-domain",
    title: "Distributed Platforms & Mastercard Domain Knowledge",
    domains: ["screen"],
    questionTypes: ["screen-payments-domain"],
    signals: ["domain-expertise", "ownership"],
    card: {
      c: "Worked at Mastercard Dublin from 2019 to 2022. Know the culture, the Dublin tech hub, and how critical infrastructure operates at Mastercard. The Distributed Platforms team focuses on Linux, Windows, VMware, Storage — core infrastructure underpinning everything.",
      a: [
        "At Mastercard: operated Kubernetes infrastructure in production, managed on-call rotations, CI/CD pipelines, DevOps practices",
        "At Citi: managed infrastructure spanning Linux environments, cloud platforms (AWS, GCP), containerized workloads, and hybrid architectures",
        "Deep experience with ITSM practices — ServiceNow for incident/change/problem management, MTTR tracking, KPI reporting",
        "Understand the compliance and operational rigour required in financial services infrastructure",
      ],
      r: "The role asks for someone to build SRE operational presence in Europe and own a key pillar (automation, observability, or resilience). That's exactly what I built at Citi — and I already know the Mastercard Dublin environment.",
      l: "Distributed Platforms SRE is about making core infrastructure — the things everything else runs on — reliable, observable, and continuously improving. That's the most impactful place for SRE leadership.",
    },
    probes: {
      "what infrastructure have you managed": "Linux and container environments primarily. Kubernetes for orchestration, VMware in hybrid setups. At Citi, managed infrastructure across AWS and GCP with Terraform. ServiceNow for ITSM workflows.",
      "what do you know about the distributed platforms team": "Core infrastructure team — Linux, Windows, VMware, Storage. The backbone that applications run on. SRE here means ensuring those platforms are resilient, observable, and automated. The European operational presence is critical because incidents don't wait for US business hours.",
    },
  },
  {
    id: "screen-questions-for-recruiter",
    title: "Questions to Ask the Recruiter",
    domains: ["screen"],
    questionTypes: ["screen-questions-for-them"],
    signals: ["communicating-effectively", "domain-expertise"],
    card: {
      c: "Always have thoughtful questions prepared — shows genuine interest and helps you evaluate the opportunity. Tailor to what a recruiter can actually answer (team structure, process, timeline — not deep technical).",
      a: [
        "What does the Distributed Platforms SRE team look like today in Dublin? How many engineers, and is this building from scratch or scaling an existing team?",
        "Which SRE pillar (automation, observability, or operational resilience) is the most urgent priority right now?",
        "What does the on-call and incident command model look like currently for Europe? Am I standing that up or inheriting something?",
        "What does success look like in the first 6-12 months for this role?",
        "What's the relationship between the Dublin SRE team and the US-based team? How are global responsibilities split?",
        "What's the core infrastructure stack today — what mix of Linux, Windows, VMware, and container platforms are we talking about?",
      ],
      r: "Pick 3-4 of these. Don't ask all of them. Listen to earlier answers — some may be addressed naturally.",
      l: "Good questions signal that you've thought about the role seriously. For a boomerang candidate, referencing your prior Mastercard experience in a question shows continuity.",
    },
    probes: {},
  },
  // ============ CITI DEPTH STORIES — How I Did It ============
  {
    id: "screen-observability-platform",
    title: "Observability Platform (OTel + Prometheus + Grafana)",
    domains: ["screen"],
    questionTypes: ["screen-observability", "screen-sre-depth", "big-tech-decision", "innovation"],
    signals: ["driving-results", "ownership", "leadership-influence"],
    card: {
      c: "Teams at Citi had fragmented monitoring — no correlation between metrics, logs, and traces across hundreds of cloud-native services. Alerts were noisy, root cause analysis was slow, and incident detection relied on tribal knowledge.",
      a: [
        "Chose OpenTelemetry as the instrumentation standard — vendor-neutral, portable, future-proof",
        "Prometheus for metrics collection and Grafana for visualization, dashboards, and alerting",
        "Built a custom correlation layer — an alert on one service traces impact across all dependent services automatically",
        "Rolled out incrementally — onboarded teams in waves with office hours and working examples, not a big-bang mandate",
        "Partnered with security to integrate observability signals into incident detection workflows",
      ],
      r: "Correlated alerting across hundreds of services. Accelerated incident detection and resolution. Became the standard observability stack for cloud-native services at Citi.",
      l: "Chose open-source over commercial (Datadog/Splunk) for cost control, vendor independence, and full ownership at Citi's scale. Made the safe path the easy path — teams adopted because it was better, not because it was mandated.",
    },
    probes: {
      "why not datadog or splunk": "Enterprise scale — commercial licensing at Citi's volume would be significant. OTel gives portability and vendor independence. Prometheus + Grafana gave the team full ownership and customization without procurement cycles.",
      "how did you get teams to adopt": "Incremental rollout — started with high-incident services, showed the value, then expanded. Office hours, example dashboards, and clear docs. Guardrails not gates.",
      "what was the hardest part": "Correlation across services. A single alert in isolation is noise — the value comes from tracing causality chains. That required a shared data model and consistent instrumentation, which meant influencing dozens of teams.",
      "how does this relate to mastercard": "Payments Network SRE needs exactly this — proactive monitoring, intelligent alerting, and correlated observability across mission-critical infrastructure. The JD literally calls out advancing observability and telemetry capabilities.",
    },
  },
  {
    id: "screen-aiops-engine",
    title: "AIOps ML Engine (SCOUT)",
    domains: ["screen"],
    questionTypes: ["screen-aiops", "innovation", "big-tech-decision"],
    signals: ["driving-results", "ownership", "growing-continuously"],
    card: {
      c: "Millions of operational records monthly across ServiceNow and CAI — different formats, critical info buried in free-text. Engineers drowning in alerts. No way to correlate incidents or spot recurring patterns across 100k+ incidents monthly.",
      a: [
        "Reframed from 'we need AI' to 'engineers can't see patterns' — data quality before model quality",
        "Normalized fragmented data from ServiceNow + CAI into a single schema — without clean data, ML produces noise",
        "AWS serverless architecture — SageMaker for managed training, 110ms latency budget for real-time triage",
        "Ensemble meta-selector model maximizing precision + recall within the latency constraint",
        "Treated internal engineering as customers — built a relevance feed, not a generic dashboard",
      ],
      r: "Repeat incidents reduced 35%. Triage time cut 55%. Precision: 68% → 89%. First real-time view of operational risk for leadership.",
      l: "Data quality before model quality. Adoption comes from treating internal users as customers. Leaned into my data science background to sharpen the ML problem framing — cluster similar incidents, not predict unreliable categories.",
    },
    probes: {
      "did you build the ml yourself": "I led architecture, data engineering, and cloud infrastructure. Also sharpened the ML problem framing — my DS background helped reframe from prediction to clustering. The team owned model development, I owned platform and direction.",
      "what was the 110ms constraint": "Real-time triage during incidents — the engine needed to classify and route within 110ms to be useful in live incident workflows. Anything slower and engineers would ignore it.",
      "how does this connect to sre": "AIOps is the evolution of observability — moving from reactive alerting to predictive analysis. The Mastercard JD calls out automated remediation and improved RCA. That's exactly what SCOUT delivers.",
    },
  },
  {
    id: "screen-kafka-flink-pipelines",
    title: "Streaming Pipelines (Kafka + Flink, 2B+ events/day)",
    domains: ["screen"],
    questionTypes: ["screen-streaming-pipelines", "big-tech-decision", "trade-offs"],
    signals: ["driving-results", "ownership", "domain-expertise"],
    card: {
      c: "Enterprise data fabric — 2B records/day, 300 sources. Batch-based pipeline with policy checks running 4-6 hours late. Security team: 'We're operating blind.' SOC2/ISO 27001 compliance at risk.",
      a: [
        "Kafka as single front door for all event ingestion — unified entry point, decoupled producers from consumers",
        "Flink for the hot path — real-time processing, windowed aggregations, in-flight governance",
        "OPA + broadcast state for policy enforcement with zero-downtime policy updates",
        "Won ARB approval through a 4-week A/B pilot — same production workload, Flink vs Spark Structured Streaming. Made ARB leads validation partners, not gatekeepers",
        "Designed streaming-native verification for governance — sliding windows + temporal aggregates replaced batch checks",
      ],
      r: "Latency 6 hours → under 1 minute. 99.9% uptime. 40% fewer nodes than Spark. Zero disruption to 300 downstream teams. Operational toil reduced 25%.",
      l: "Hardest part wasn't tech — it was organizational inertia. ARB blocked Flink initially. Earned approval by framing it as a safe experiment with clear exit criteria, not a platform bet. CTO cited the validation framework as 'blueprint for responsible innovation.'",
    },
    probes: {
      "why flink over spark": "True streaming not micro-batch. Better state management. Millisecond latency. The 4-week pilot data spoke for itself — 99.9% uptime, 40% fewer nodes, and sub-minute latency vs 6 hours.",
      "how did you handle the arb pushback": "Stopped arguing technical superiority. Acknowledged their risk framing. Proposed a data-driven partnership — a pilot with instrumented metrics for their concerns (P99, cost, SLA compliance). Made them validation partners. Clear exit criteria if Flink underperformed.",
      "how did you manage 300 teams": "Didn't ask them to change anything. Kafka as single front door meant producers onboarded through a standard interface. Flink processed transparently downstream. Coexisted with Spark — Iceberg as the peace treaty between batch and streaming.",
    },
  },
  {
    id: "screen-scaling-global-org",
    title: "Scaling the Global Engineering Org (10 → 20)",
    domains: ["screen"],
    questionTypes: ["screen-scaling-org", "scaling", "growing-team", "good-em"],
    signals: ["leadership-influence", "mentorship", "driving-results"],
    card: {
      c: "Org doubled from roughly 10 to 20 engineers in a year — engineers and contractors across US, Europe, India. Couldn't add formal managers. Delivery needed structure but hierarchy wasn't an option.",
      a: [
        "Created a Tech Lead Operating Model — 5 senior ICs each owning a domain as player-coaches",
        "Defined clear swimlanes — ownership boundaries + interfaces between streams",
        "Bi-weekly Tech Lead Forum for priorities, dependencies, resourcing decisions",
        "Weekly 1:1s coaching each lead on stakeholder management, estimation, conflict resolution",
        "OKRs + DORA metrics + say/do ratio as the operating framework — measure the system, not the humans",
      ],
      r: "Delivery capacity scaled 2x in 6 months. Zero management overhead added. One tech lead promoted to EM. Model became blueprint adopted by two other Citi organizations.",
      l: "Leadership isn't about titles — it's about creating a system where accountability, decision-making, and trust scale faster than hierarchy. At Director level, my impact isn't what I build — it's the system I create for others to deliver at scale.",
    },
    probes: {
      "how did you pick the tech leads": "Identified engineers already informally leading. Formalized it with clear domain ownership, decision rights, and coaching investment. Picked for judgment and communication, not just technical depth.",
      "how did you handle remote teams": "Written culture for decisions, async design reviews, time-zone-aware meeting cadences. Tech Lead Forum bridged gaps. Trust-based — set clear outcomes, let people own the how.",
      "what about contractors": "Output improved significantly — communication flowed through empowered leads rather than waiting for top-down direction. Clear swimlanes meant contractors had the same clarity as full-time engineers.",
    },
  },
  {
    id: "screen-incident-response-citi",
    title: "Incident Response & Blameless Postmortems",
    domains: ["screen"],
    questionTypes: ["screen-incident-response", "high-stakes-call", "fw-incident-management"],
    signals: ["ownership", "leadership-influence", "driving-results"],
    card: {
      c: "No structured incident response or postmortem practice across cloud technology services at Citi. Teams handled incidents ad hoc — inconsistent communication, repeated failures, no systemic learning.",
      a: [
        "Defined clear incident roles — incident commander, comms lead, technical responder. No ambiguity during chaos",
        "15-minute leadership updates during incidents — keeps them informed without disrupting engineers",
        "Restore first, root-cause later — never debug while services are down",
        "Blameless postmortem within 48 hours — focus on systemic fixes, not who made the mistake",
        "Action items must prevent recurrence — monitoring, automation, runbooks. 'Be more careful' is never an action item",
      ],
      r: "Eliminated repeat incidents across owned services. Improved production readiness. Reduced operational risk organization-wide.",
      l: "Incident management isn't about firefighting — it's about building a system where the org learns from every failure. The Mastercard JD calls out owning incident response frameworks and reducing MTTR — this is exactly what I built.",
    },
    probes: {
      "give me a specific incident example": "Kafka OOM at 3am — entire messaging infra down, dozens of services impacted. Convened bridge call, split team into root cause, remediation, and comms. Service restored in 45 minutes. Post-mortem drove automated heap monitoring, self-healing scripts, and eventually migration to MSK.",
      "how do you measure incident management": "MTTR, incident frequency, recurrence rate, and time to postmortem. Also qualitative — do engineers feel safe raising issues early? That's the culture metric.",
      "what about chaos engineering": "We built production readiness reviews and automated remediation patterns. Chaos engineering is the next evolution — the Mastercard role's emphasis on it aligns with where I want to push the practice.",
    },
  },
  {
    id: "screen-cross-functional-citi",
    title: "Cross-Functional Partnership & Executive Communication",
    domains: ["screen"],
    questionTypes: ["screen-cross-functional", "fw-stakeholder-management", "roadmap"],
    signals: ["communicating-effectively", "leadership-influence", "driving-results"],
    card: {
      c: "SRE and observability priorities needed alignment with engineering, product, and security — each with different definitions of success. Required regular presentation of roadmap progress and trade-offs to senior leadership (CTOEAC).",
      a: [
        "Stakeholder mapping (power/interest grid) — tailored cadence and detail level for each audience",
        "Translated tech to business impact: 'observability platform' becomes 'reducing MTTR by 40% and cutting incident escalations'",
        "No surprises rule — surface risks early with mitigation options, not just bad news",
        "Aligned observability priorities with each partner: security got faster incident detection, product got reliability SLAs, engineering got reduced toil",
        "Regular CTOEAC presentations — roadmap progress, trade-offs, and investment recommendations",
      ],
      r: "Aligned three organizations around shared observability goals. Earned budget for platform investments. Leadership trusted the team to make autonomous technical decisions.",
      l: "At Director level, the job is as much about influence and communication as it is about technology. The Mastercard role requires partnering with Product, Architecture, Security, and Development — this is exactly the muscle I've been building.",
    },
    probes: {
      "what is ctoeac": "CTO Executive Advisory Committee — senior leadership forum where technology leaders present strategy, progress, and trade-offs. I presented our observability and SRE roadmap regularly.",
      "how do you handle competing priorities": "RICE scoring to quantify, cost-of-delay analysis to create urgency, and 'here's what we'd drop to fit this in' to make trade-offs visible. Never debate opinions — debate data.",
      "how do you manage up": "Tailor the message to the audience. Execs want business impact and risk. Peers want technical detail. Reports want context and direction. Same initiative, different lens.",
    },
  },
];

const QUESTION_KEYWORDS = {
  "tough-project":    ["hardest project", "most complex", "challenging project", "toughest", "most difficult project", "complex project", "big project"],
  "deadlines":        ["deadline", "tight timeline", "time pressure", "crunch", "behind schedule", "shipped on time"],
  "blockers":         ["blocked", "obstacle", "unblock", "stuck", "impediment", "bottleneck"],
  "trade-offs":       ["trade-off", "tradeoff", "competing priorities", "difficult decision", "had to choose", "weigh options"],
  "high-stakes-call": ["high stakes", "production issue", "outage", "incident", "on-call", "critical situation", "pressure"],
  "roadmap":          ["roadmap", "prioritize", "planning", "what to build next", "sequencing"],
  "failure":          ["tell me about a failure", "biggest mistake", "something that didn't work", "learned the hard way", "setback", "went wrong", "a time you failed"],
  "big-tech-decision":["technical decision", "technology choice", "architecture decision", "why did you pick", "tech stack decision"],
  "scaling":          ["scaling challenge", "scaled the system", "team growth", "doubled the team", "expanded the team", "larger team"],
  "innovation":       ["innovate", "creative solution", "new approach", "improve process", "better way to", "ran an experiment"],
  "conflict":         ["conflict with", "disagree with", "pushback from", "tension between", "difficult stakeholder", "resistance from"],
  "underperformance": ["underperform", "not meeting expectations", "low performer", "performance issue", "pip", "difficult conversation with report"],
  "growing-team":     ["build a team", "hiring for", "grew the team", "team structure", "org design", "onboarding"],
  "motivating-team":  ["motivate the team", "team morale", "team engagement", "inspire the team", "burned out team", "low energy"],
  "good-em":          ["what makes a good manager", "management style", "leadership philosophy", "how do you lead", "management approach"],
  "culture-impact":   ["team culture", "culture change", "psychological safety", "inclusion", "built a culture"],
  "above-and-beyond": ["above and beyond", "extra mile", "took initiative", "beyond your role", "stepped up"],
  "results":          ["measurable outcome", "metrics you drove", "results you're proud of", "biggest achievement", "biggest accomplishment"],
  "screen-intro":              ["tell me about yourself", "walk me through your background", "introduce yourself", "about your experience", "your career journey", "walk me through your resume", "walk me through your cv", "tell us about yourself"],
  "screen-why-role":           ["why mastercard", "why this role", "what interests you about", "why this position", "why are you interested", "why come back", "why apply", "attracted to this role", "what drew you", "why do you want to work"],
  "screen-why-leave":          ["why leaving", "why are you looking", "why move", "why change", "what's prompting", "what brings you here", "why leave citi", "thinking of leaving"],
  "screen-leadership-scope":   ["team size", "how many people", "direct reports", "org structure", "who reports to you", "how big is your team", "scope of your role", "how many engineers"],
  "screen-sre-depth":          ["sre experience", "reliability engineering experience", "observability experience", "incident management experience", "platform engineering", "your sre background", "site reliability"],
  "screen-payments-domain":    ["payments experience", "payments infrastructure", "payment systems", "financial services", "transaction processing", "what do you know about payments"],
  "screen-questions-for-them": ["do you have any questions", "questions for us", "anything you want to ask", "what would you like to know"],
  "screen-observability":      ["observability", "monitoring", "alerting", "prometheus", "grafana", "opentelemetry", "dashboards", "metrics platform", "telemetry platform", "how do you monitor"],
  "screen-aiops":              ["aiops", "ml engine", "machine learning", "predictive", "incident prediction", "automated remediation", "text analytics", "servicenow analytics", "reduce incidents"],
  "screen-streaming-pipelines":["kafka", "flink", "streaming", "event pipeline", "real-time pipeline", "data pipeline", "event processing", "batch to streaming", "two billion"],
  "screen-scaling-org":        ["scaling the org", "growing the team", "built the team", "how did you scale", "team structure", "operating model", "tech lead model", "org design at citi"],
  "screen-incident-response":  ["incident response", "postmortem", "on-call", "production incident", "blameless", "mttr", "incident management", "how do you handle incidents", "outage response"],
  "screen-cross-functional":   ["cross-functional", "stakeholder", "executive communication", "working with product", "working with security", "ctoeac", "present to leadership", "roadmap presentation"],
};

const FRAMEWORKS = [
  {
    id: "fw-high-performing-team",
    questionType: "fw-high-performing-team",
    definition: "A high-performing team delivers outsized impact through clarity, trust, and accountability — not heroics.",
    pillars: [
      "Clear ownership and swimlanes — every engineer knows their domain and interfaces",
      "Psychological safety — people raise risks early, not after it's too late",
      "Metrics-driven delivery — DORA metrics, say/do ratio, not hours worked",
      "Coaching culture — 1:1s focused on growth, not status updates",
      "Aligned incentives — team OKRs over individual credit",
    ],
    storyLink: "scaling-teams",
    signals: ["leadership-influence", "mentorship"],
  },
  {
    id: "fw-management-style",
    questionType: "fw-management-style",
    definition: "Context-driven leadership — high support for new or ambiguous situations, high autonomy for proven teams.",
    pillars: [
      "Situational leadership — flex between coaching, directing, and delegating based on team maturity",
      "Default to trust — set clear outcomes, let people own the how",
      "Radical candor — care personally, challenge directly. Never defer hard conversations",
      "Data over gut — use sprint velocity, lead time, and feedback signals to calibrate",
      "Shield and empower — absorb organizational noise so the team can focus on delivery",
    ],
    storyLink: "underperformer-coach-up",
    signals: ["leadership-influence", "mentorship"],
  },
  {
    id: "fw-scaling-org",
    questionType: "fw-scaling-org",
    definition: "Scaling is about building systems that distribute decision-making, not about adding more people.",
    pillars: [
      "Domain-aligned teams with clear ownership boundaries and minimal cross-team dependencies",
      "Tech Lead operating model — player-coaches who own delivery, not just architecture",
      "Lightweight governance — shared OKRs, bi-weekly forums, visible dashboards",
      "Hiring for slope, not intercept — potential and learning speed over current skill",
      "Written culture — decisions, context, and rationale documented so knowledge scales beyond meetings",
    ],
    storyLink: "scaling-teams",
    signals: ["leadership-influence", "driving-results"],
  },
  {
    id: "fw-strategy-to-delivery",
    questionType: "fw-strategy-to-delivery",
    definition: "Translating strategy into delivery is about creating line-of-sight — every team sees how its work ladders to the outcome — not cascading targets downward.",
    pillars: [
      "Start with the outcome and the WHY, not the task — what we're trying to achieve and why it matters",
      "Work backwards from the strategic metric to the operational drivers teams can actually move",
      "Make ownership and line-of-sight explicit — people buy into why targets matter, not the targets themselves",
      "Sequence by business value — deliver where it matters most first; those teams become reference adopters that build momentum",
      "Feedback loops, adapt fast — find root cause when it drifts and adjust the plan rather than letting problems grow",
      "Recognize results — recognition reinforces the behaviors that produced them",
    ],
    storyLink: "eb-tech-drift",
    signals: ["leadership-influence", "driving-results"],
  },
  {
    id: "fw-operational-balance",
    questionType: "fw-operational-balance",
    definition: "Keeping the lights on isn't leftover work — it's a budgeted line item that defends feature velocity, not something that competes with it.",
    pillars: [
      "Budget KTLO explicitly — a deliberate, planned slice of capacity for operational work, reliability, and tech debt (often 20-30%); the number isn't the point, planning it is",
      "Let data set the dial — SLOs and error budgets: burning the error budget is an objective signal to slow features and invest in reliability",
      "Make the tradeoff visible — frame it for stakeholders as a shared decision: 'if we don't address X, here's the incident / churn / security exposure'",
      "Protect against the death spiral — under-investing in KTLO kills feature velocity too (neglected systems generate more incidents, more interruptions), so reliability investment defends throughput, it doesn't compete with it",
    ],
    storyLink: "eb-mgmt-ktlo",
    signals: ["driving-results", "ownership"],
  },
  {
    id: "fw-stakeholder-management",
    questionType: "fw-stakeholder-management",
    definition: "Stakeholder management is about creating shared understanding, not managing expectations down.",
    pillars: [
      "Power/interest mapping — tailor cadence and detail level to each stakeholder's needs",
      "Translate tech to business impact — 'database migration' becomes 'reducing outage risk by 60%'",
      "No surprises rule — surface risks early with mitigation options, not just bad news",
      "RACI on every deliverable — eliminate ambiguity about who decides vs. who's informed",
      "Build trust through small wins — deliver incrementally, show progress, earn credibility for bigger asks",
    ],
    storyLink: "architecture-alignment-greg",
    signals: ["communicating-effectively", "leadership-influence"],
  },
  {
    id: "fw-technical-excellence",
    questionType: "fw-technical-excellence",
    definition: "Technical excellence means the safe path is the easy path — quality is a system property, not individual discipline.",
    pillars: [
      "Golden paths and guardrails — opinionated defaults with escape hatches for edge cases",
      "Shift-left everything — policy-as-code in CI/CD, not manual review gates",
      "DORA metrics as compass — deploy frequency, lead time, change failure rate, MTTR",
      "Code review as teaching — PRs are learning opportunities, not gatekeeping",
      "Tech debt as first-class work — budget 20% capacity for platform health, not just features",
    ],
    storyLink: "terraform-golden-path",
    signals: ["driving-results", "ownership"],
  },
  {
    id: "fw-handling-ambiguity",
    questionType: "fw-handling-ambiguity",
    definition: "In ambiguity, alignment comes before architecture — define the 'why' before debating the 'how'.",
    pillars: [
      "Start with stakeholder intent — 'what decision are you trying to make with this?'",
      "Decompose into knowns and unknowns — build on knowns, spike on unknowns",
      "Time-box exploration — 2-week spikes with clear exit criteria, not open-ended research",
      "Make reversible decisions fast — only slow down for one-way doors",
      "Communicate assumptions explicitly — document what you're betting on and revisit",
    ],
    storyLink: "app-dependencies",
    signals: ["handling-ambiguity", "ownership"],
  },
  {
    id: "fw-prioritization",
    questionType: "fw-prioritization",
    definition: "Prioritization is about saying no to good things so you can say yes to the right things.",
    pillars: [
      "RICE scoring — Reach, Impact, Confidence, Effort. Quantify, don't debate opinions",
      "Cost of delay — what's the business impact of NOT doing this now?",
      "Sequence by dependencies — unblock others first, then parallelize",
      "Say no with data — 'here's what we'd drop to fit this in' makes the trade-off visible",
      "Re-prioritize regularly — weekly triage, not quarterly planning that goes stale",
    ],
    storyLink: "conflicting-requirements",
    signals: ["driving-results", "communicating-effectively"],
  },
  {
    id: "fw-engineering-culture",
    questionType: "fw-engineering-culture",
    definition: "Great engineering culture is where people do the right thing because the environment makes it natural, not because someone's watching.",
    pillars: [
      "Psychological safety — people experiment, fail, and learn without blame",
      "Inclusive by design — rotating leads, async input, diverse panels",
      "Innovation time — structured spikes, not hackathons and slogans",
      "Blameless post-mortems — fix the system, not the person",
      "Celebrate learning velocity — reward growth and curiosity, not just output",
    ],
    storyLink: "inclusive-leadership",
    signals: ["leadership-influence", "growing-continuously"],
  },
  {
    id: "fw-incident-management",
    questionType: "fw-incident-management",
    definition: "Incident management is about restoring service first, then learning — never blame.",
    pillars: [
      "Clear roles on the bridge — incident commander, comms lead, technical responder",
      "Restore first, root-cause later — don't debug while customers are down",
      "Timed leadership updates — every 15 min so they don't disrupt the engineers",
      "Blameless post-mortem within 48 hours — focus on systemic fixes, not who made the mistake",
      "Action items that prevent recurrence — monitoring, automation, runbooks, not 'be more careful'",
    ],
    storyLink: "kafka-oom",
    signals: ["ownership", "leadership-influence"],
  },
  {
    id: "fw-decision-making",
    questionType: "fw-decision-making",
    definition: "Good technical decisions are evidence-based, time-bound, and reversible where possible.",
    pillars: [
      "One-way vs two-way doors — only slow down for irreversible decisions",
      "Data-driven validation — POC or A/B pilot before committing, not opinion wars",
      "Include operators — the people who run it in production have veto power on operational complexity",
      "Document the decision and alternatives — future you needs to know WHY, not just WHAT",
      "Set exit criteria — define upfront what failure looks like and when to pivot",
    ],
    storyLink: "kafka-vs-solace",
    signals: ["driving-results", "communicating-effectively"],
  },
];

const FRAMEWORK_KEYWORDS = {
  "fw-high-performing-team":   ["high performing team", "great team", "what makes a team", "team effectiveness", "effective team", "define a team", "build a great team", "high performance"],
  "fw-management-style":       ["management style", "management philosophy", "how do you manage", "leadership style", "what kind of manager", "what kind of leader", "describe your style", "your approach to managing"],
  "fw-scaling-org":            ["scale an org", "scaling organization", "grow an organization", "org scaling", "scale engineering org", "growing the org", "org structure"],
  "fw-stakeholder-management": ["manage stakeholders", "stakeholder management", "work with stakeholders", "manage up", "align stakeholders", "executive communication", "manage expectations"],
  "fw-strategy-to-delivery":   ["translate strategy", "strategy into delivery", "strategy into operational delivery", "strategy to execution", "strategy into execution", "operational delivery", "company strategy", "turn strategy into", "vision to execution", "execute the strategy"],
  "fw-operational-balance":    ["keeping the lights on", "keep the lights on", "keeping the light on", "lights on", "ktlo", "run the business", "business as usual", "operational vs", "operational work vs", "tech debt vs features", "reliability vs features", "maintenance vs new", "balance operational", "balance reliability", "balance keeping"],
  "fw-technical-excellence":   ["technical excellence", "engineering excellence", "good engineering", "quality engineering", "define excellence", "engineering standards", "what does good look like"],
  "fw-handling-ambiguity":     ["handle ambiguity", "deal with ambiguity", "approach to ambiguity", "navigate uncertainty", "unclear requirements", "when things are unclear", "ambiguous situation"],
  "fw-prioritization":         ["how do you prioritize", "prioritization framework", "decide what to work on", "competing priorities", "prioritize your work", "what do you work on first", "how to prioritize"],
  "fw-engineering-culture":    ["engineering culture", "team culture", "define culture", "build culture", "what does good culture", "healthy culture", "culture look like"],
  "fw-incident-management":    ["incident management", "approach to incidents", "handle incidents", "incident response", "on-call philosophy", "manage outages", "production incidents"],
  "fw-decision-making":        ["decision making", "make decisions", "approach to decisions", "decision framework", "how do you decide", "technical decisions", "making technical choices"],
};

// ---- Tech-screen prep merge (additive; see dev/tech-screen-stories.js) ----
// Appends Mastercard Hiring-Team Tech-Screen material without modifying any
// existing entry above. Remove this block + the file to fully revert.
const {
  TECH_SCREEN_QUESTION_TYPES,
  TECH_SCREEN_CATEGORY,
  TECH_SCREEN_STORIES,
  TECH_SCREEN_KEYWORDS,
} = require("./tech-screen-stories");
Object.assign(QUESTION_TYPES, TECH_SCREEN_QUESTION_TYPES);
Object.assign(CATEGORIES, TECH_SCREEN_CATEGORY);
Object.assign(QUESTION_KEYWORDS, TECH_SCREEN_KEYWORDS);
STORIES.push(...TECH_SCREEN_STORIES);

// The 49 pillar Q&As (single source: pillar-cards.js) — surfaced live by the
// classifier and rendered on the prep page from the same data.
const {
  PILLAR_QUESTION_TYPES,
  PILLAR_CATEGORY,
  PILLAR_STORIES,
  PILLAR_KEYWORDS,
} = require("./pillar-cards");
Object.assign(QUESTION_TYPES, PILLAR_QUESTION_TYPES);
Object.assign(CATEGORIES, PILLAR_CATEGORY);
Object.assign(QUESTION_KEYWORDS, PILLAR_KEYWORDS);
STORIES.push(...PILLAR_STORIES);
// ---------------------------------------------------------------------------

module.exports = { SIGNALS, CATEGORIES, QUESTION_TYPES, STORIES, QUESTION_KEYWORDS, FRAMEWORKS, FRAMEWORK_KEYWORDS };
